<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Snowplow\\RefererParser' => array($vendorDir . '/snowplow/referer-parser/php/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'Requests' => array($vendorDir . '/rmccue/requests/library'),
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib'),
    'Orangehill\\Iseed' => array($vendorDir . '/orangehill/iseed/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'DevMarketer\\EasyNav' => array($vendorDir . '/devmarketer/easynav/src'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
    'Braintree' => array($vendorDir . '/braintree/braintree_php/lib'),
    'Bllim\\Datatables' => array($vendorDir . '/pragmarx/datatables/src'),
);
